# Generated by Django 4.1.3 on 2023-03-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSV', '0002_contactar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactar',
            name='Usuario',
            field=models.CharField(max_length=255),
        ),
    ]
